# Generated by Django 4.1.1 on 2022-09-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmakesapp', '0002_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='img1',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
