# Generated by Django 4.1.1 on 2022-09-26 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmakesapp', '0003_alter_person_img1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='desc1',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='img1',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name1',
            new_name='name',
        ),
    ]
